### ISSUE TITLE
Backups not working properly??

### ISSUE THREAD

**Issue by pkkid** [endofzero/Minecraft-Sheller#6]
Another possible issue..

I setup a cronjob to run a backup every night using the cron-line:
0 5 \* \* \*   /opt/minecraft/minecraft.sh backup clean 

In my minecraft.sh settings I have the following:
BKUP_DAYS_INCR=2
BKUP_DAYS_FULL=5

I noticed after 10 days that I only had 1 full backup and 9 incr backups.  This doesn't seem to follow the rules defined here.  I am no bash scripter, but looking at the backup section in the script, I am thinking the culprit line might be this:

line 228: if test `date +%H` -eq 0 -o ! -f $BACKUP_FULL_LINK

It seems like its always failing this test after the full backup exists and not taking into consideration BKUP_DAYS_FULL.  Also, there doesn't seem to be any reference to the [clean] option in the backup section.  Is this a phantom option?

**Comment by endofzero** [comment]
I will do some testing with the backups, line 228 is pretty much saying, 'Only do a full backup if it is 12:00am - 12:59am when ran' Not sure what the logic was behind that part.

Clean does have an option catch inside of the backup...

case $2 in
"clean")
DATE=$(date +%d-%m --date "$LOGS_DAYS day ago")
if [ -e logs-$DATE ]
then
mkdir -p $BKUP_PATH/logs
mv logs-$DATE $BKUP_PATH/logs/
fi
;;
esac

**Comment by pkkid** [comment]
Maybe I should be running my cronjob once an hour then?

**Comment by endofzero** [comment]
Ok, this has been fixed. The cleanup was never adjusted after it was changed from just full backups to incremental backups.

So to run a full backup (which also drops the old archives at that point) then run 'minecraft.sh backup full'
otherwise you can just run 'minecraft.sh backup' to make an incremental backup.

So really how it was intended was to run just 'backup' every 30-60 minutes or what have you and 'backup full' to run a full backup and truncate the old ones once a day.
