### ISSUE TITLE
Make Minecraft-Sheller upstart compatible!

### ISSUE THREAD

**Issue by robbiet480** [endofzero/Minecraft-Sheller#8]
You know, so I can run /etc/init.d/minecraft and its the same thing except for the fact the system controls it at startup/shutdown

**Comment by endofzero** [comment]
There are a bunch of problems with using screen and starting a session when you are hitting a runlevel since you would have to 'su' to the minecraft user and screen will call foul about not having a terminal to attach to. I don't think this would be viable in most environments as you are running minecraft as an isolated user, as opposed to root. I'm going to close this as denied on the basis you would probably have to go with a solution other then 'screen'.
